my_novels/urls.py
from django.urls import path
from . import views

app_name = 'my_novels'
urlpatterns = [
    path('hello', views.hello_world, name='hello'),
    path('', views.list, name='list'),
    path('novel/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('novel/<int:pk>/delete', views.delete, name='delete'),
    path('novel/create', views.create, name='create')
]

project_novels/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_novels.urls')),
]

my_novels/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Novel(models.Model):
    title = models.CharField(max_length=32)
    description = models.CharField(max_length=256)
    body = models.CharField(max_length=2048)
    genre = models.ManyToManyField(Genre)

    def __str__(self):
        return self.title

my_novels/forms.py
from django import forms

class CreateForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=32)
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), max_length=256)
    #body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), max_length=2048)
    genres = forms.ModelMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'checkbox-inline'})
    )

    def __init__(self, *args, **kwargs):
        genres = kwargs.pop('genres', None)
        super(CreateForm, self).__init__(*args, **kwargs)
        
        if genres is not None:
            self.fields['genres'].queryset = genres

my_novels/controllers/chatgpt.py
from openai import OpenAI

client = OpenAI(api_key='')

def bodyGenerator(description, genres):
    messages = [
        {
            "role": "system", "content": "Sei un assistente che genera una storia data una descrizione e un set di generi"
        },
        {
            "role": "system", "content": "I generi sono: " + ', '.join(genres)
        },
        {
            "role": "user", "content": description
        }
    ]

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=messages,
            max_tokens=1024
        )

        return response.choices[0].message.content
    except Exception as e:
        print(f'Error openai: {e}')

my_novels/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views import generic

from .models import Novel, Genre

def hello_world(request):
    return HttpResponse('Hello World')

def list(request):
    novels = Novel.objects.all()
    return render(request, 'my_novels/list.html', {'novels': novels})

class DetailView(generic.DetailView):
    model = Novel
    template_name = "my_novels/detail.html"

def delete(request, pk):
    novel = Novel.objects.get(pk = pk)
    novel.delete()

    return redirect('my_novels:list')

from .forms import CreateForm
from .controllers.chatgpt import bodyGenerator

def create(request):
    genres = Genre.objects.all()

    if request.method == 'POST':
        form = CreateForm(request.POST, genres = genres)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            form_genres = form.cleaned_data['genres'] #relation N a N

            body = bodyGenerator(description=description, genres=[genre.name for genre in form_genres])

            new_novel = Novel.objects.create(title=title, description=description, body=body)

            new_novel.genre.set(form_genres)
            new_novel.save()

            return redirect('my_novels:list')
        
    form = CreateForm(genres = genres)
    return render(request, 'my_novels/create.html', {'form': form})

my_novels/templates/base_template.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Default title{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- GOOGLE FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    <!-- END GOOGLE FONT -->
</head>
<body>
    <header>
        {% block header %}<h1>Header</h1>{% endblock %}
    </header>

    <main>
        {% block main %}{% endblock %}
    <main>

    <footer>
    </footer>
</body>
</html>

my_novels/templates/my_novels/card.html
{% load static %}
<a class="card" href="{% url 'my_novels:detail' novel.id %}">
    <h2>{{ novel.title }}</h2>
    <div class="genres">
        {% for genre in novel.genre.all %}
        <div class="genre">{{ genre.name }}</div>
        {% endfor %}
    </div>

    <p>{{ novel.description }}</p>
    
</a>

my_novels/templates/my_novels/create.html
{% extends 'base_template.html' %}

{% block title %}{{novel.title}}{% endblock %}

{% block header %}
    <div class="header-wrapper">
        <h1>My Novels</h1>
    </div>
{% endblock %}

{% block main %}
{% load static %}
<div class="back-to-previous-page-wrapper">
    <a href="{% url 'my_novels:list' %}" class="back-to-previous-page"> < Page List</a>
</div>
<div class="new-novel-form-wrapper">
    <form class="new-novel-form" action="{% url 'my_novels:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn create-form-submit" type="submit" value="Create">
    </form>
</div>
{% endblock %}

my_novels/templates/my_novels/detail.html
{% extends 'base_template.html' %}

{% block title %}{{novel.title}}{% endblock %}

{% block header %}
    <div class="header-wrapper">
        <h1>My Novels</h1>
    </div>
{% endblock %}

{% block main %}
{% load static %}
<div class="back-to-previous-page-wrapper">
    <a href="{% url 'my_novels:list' %}" class="back-to-previous-page"> < Page List</a>
</div>
<div class="card-detail">
    <div class="card" href="#">
        <h2>{{novel.title}}</h2>
        <div class="genres">
            {% for genre in novel.genre.all %}
            <div class="genre">{{genre.name}}</div>
            {% endfor %}
        </div>
        <p>
            {{novel.body}}
        </p>
        <a href="{% url 'my_novels:delete' novel.id %}"><img class="icon icon-trash delete-novel" src="{% static 'images/trash.svg' %}" /></a>
    </div>
</div>
{% endblock %}

my_novels/templates/my_novels/list.html
{% extends 'base_template.html' %}

{% block title %}Novel list{% endblock %}

{% block header %}
    <div class="header-wrapper">
        <h1>My Novels</h1>
        <a href="{% url 'my_novels:create' %}" class="btn create-novel">Create new Novel</a>
    </div>
{% endblock %}

{% block main %}
    <div class="card-wrapper">
        {% for novel in novels %}
            {% include 'my_novels/card.html' with novel=novel %}
        {% endfor %}
    </div>
{% endblock %}